// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AthletesRequest.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Networking.Protocols.Protobuf {

  /// <summary>Holder for reflection information generated from AthletesRequest.proto</summary>
  public static partial class AthletesRequestReflection {

    #region Descriptor
    /// <summary>File descriptor for AthletesRequest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AthletesRequestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVBdGhsZXRlc1JlcXVlc3QucHJvdG8SHU5ldHdvcmtpbmcuUHJvdG9jb2xz",
            "LlByb3RvYnVmGhNBdGhsZXRlc01vZGVsLnByb3RvItsCCg9BdGhsZXRlc1Jl",
            "cXVlc3QSSAoEdHlwZRgBIAEoDjI6Lk5ldHdvcmtpbmcuUHJvdG9jb2xzLlBy",
            "b3RvYnVmLkF0aGxldGVzUmVxdWVzdC5SZXF1ZXN0VHlwZRIyCgR1c2VyGAIg",
            "ASgLMiQuTmV0d29ya2luZy5Qcm90b2NvbHMuUHJvdG9idWYuQWRtaW4SMwoF",
            "Y2hpbGQYAyABKAsyJC5OZXR3b3JraW5nLlByb3RvY29scy5Qcm90b2J1Zi5D",
            "aGlsZBIPCgdldmVudElEGAQgASgFEgwKBGRhdGEYBSABKAkidgoLUmVxdWVz",
            "dFR5cGUSCwoHVW5rbm93bhAAEgkKBUxvZ2luEAESCgoGTG9nb3V0EAISDQoJ",
            "U2F2ZUNoaWxkEAMSEgoORmlsdGVyQ2hpbGRyZW4QBBINCglHZXRFdmVudHMQ",
            "BRIRCg1Db3VudENoaWxkcmVuEAZiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Networking.Protocols.Protobuf.AthletesModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Networking.Protocols.Protobuf.AthletesRequest), global::Networking.Protocols.Protobuf.AthletesRequest.Parser, new[]{ "Type", "User", "Child", "EventID", "Data" }, null, new[]{ typeof(global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AthletesRequest : pb::IMessage<AthletesRequest> {
    private static readonly pb::MessageParser<AthletesRequest> _parser = new pb::MessageParser<AthletesRequest>(() => new AthletesRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AthletesRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Networking.Protocols.Protobuf.AthletesRequestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AthletesRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AthletesRequest(AthletesRequest other) : this() {
      type_ = other.type_;
      user_ = other.user_ != null ? other.user_.Clone() : null;
      child_ = other.child_ != null ? other.child_.Clone() : null;
      eventID_ = other.eventID_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AthletesRequest Clone() {
      return new AthletesRequest(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType type_ = global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 2;
    private global::Networking.Protocols.Protobuf.Admin user_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Networking.Protocols.Protobuf.Admin User {
      get { return user_; }
      set {
        user_ = value;
      }
    }

    /// <summary>Field number for the "child" field.</summary>
    public const int ChildFieldNumber = 3;
    private global::Networking.Protocols.Protobuf.Child child_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Networking.Protocols.Protobuf.Child Child {
      get { return child_; }
      set {
        child_ = value;
      }
    }

    /// <summary>Field number for the "eventID" field.</summary>
    public const int EventIDFieldNumber = 4;
    private int eventID_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int EventID {
      get { return eventID_; }
      set {
        eventID_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 5;
    private string data_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AthletesRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AthletesRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!object.Equals(User, other.User)) return false;
      if (!object.Equals(Child, other.Child)) return false;
      if (EventID != other.EventID) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType.Unknown) hash ^= Type.GetHashCode();
      if (user_ != null) hash ^= User.GetHashCode();
      if (child_ != null) hash ^= Child.GetHashCode();
      if (EventID != 0) hash ^= EventID.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (user_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(User);
      }
      if (child_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Child);
      }
      if (EventID != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(EventID);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (user_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(User);
      }
      if (child_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Child);
      }
      if (EventID != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(EventID);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AthletesRequest other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType.Unknown) {
        Type = other.Type;
      }
      if (other.user_ != null) {
        if (user_ == null) {
          User = new global::Networking.Protocols.Protobuf.Admin();
        }
        User.MergeFrom(other.User);
      }
      if (other.child_ != null) {
        if (child_ == null) {
          Child = new global::Networking.Protocols.Protobuf.Child();
        }
        Child.MergeFrom(other.Child);
      }
      if (other.EventID != 0) {
        EventID = other.EventID;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Networking.Protocols.Protobuf.AthletesRequest.Types.RequestType) input.ReadEnum();
            break;
          }
          case 18: {
            if (user_ == null) {
              User = new global::Networking.Protocols.Protobuf.Admin();
            }
            input.ReadMessage(User);
            break;
          }
          case 26: {
            if (child_ == null) {
              Child = new global::Networking.Protocols.Protobuf.Child();
            }
            input.ReadMessage(Child);
            break;
          }
          case 32: {
            EventID = input.ReadInt32();
            break;
          }
          case 42: {
            Data = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AthletesRequest message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum RequestType {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Login")] Login = 1,
        [pbr::OriginalName("Logout")] Logout = 2,
        [pbr::OriginalName("SaveChild")] SaveChild = 3,
        [pbr::OriginalName("FilterChildren")] FilterChildren = 4,
        [pbr::OriginalName("GetEvents")] GetEvents = 5,
        [pbr::OriginalName("CountChildren")] CountChildren = 6,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
