// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AthletesModel.proto

package Networking.Protocols.Protobuf;

public final class AthletesModel {
  private AthletesModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChildOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Networking.Protocols.Protobuf.Child)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <code>int32 idEvent1 = 4;</code>
     * @return The idEvent1.
     */
    int getIdEvent1();

    /**
     * <code>int32 idEvent2 = 5;</code>
     * @return The idEvent2.
     */
    int getIdEvent2();
  }
  /**
   * Protobuf type {@code Networking.Protocols.Protobuf.Child}
   */
  public  static final class Child extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Networking.Protocols.Protobuf.Child)
      ChildOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Child.newBuilder() to construct.
    private Child(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Child() {
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Child();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Child(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 32: {

              idEvent1_ = input.readInt32();
              break;
            }
            case 40: {

              idEvent2_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Child_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Child_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Networking.Protocols.Protobuf.AthletesModel.Child.class, Networking.Protocols.Protobuf.AthletesModel.Child.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <code>int32 age = 3;</code>
     * @return The age.
     */
    public int getAge() {
      return age_;
    }

    public static final int IDEVENT1_FIELD_NUMBER = 4;
    private int idEvent1_;
    /**
     * <code>int32 idEvent1 = 4;</code>
     * @return The idEvent1.
     */
    public int getIdEvent1() {
      return idEvent1_;
    }

    public static final int IDEVENT2_FIELD_NUMBER = 5;
    private int idEvent2_;
    /**
     * <code>int32 idEvent2 = 5;</code>
     * @return The idEvent2.
     */
    public int getIdEvent2() {
      return idEvent2_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (idEvent1_ != 0) {
        output.writeInt32(4, idEvent1_);
      }
      if (idEvent2_ != 0) {
        output.writeInt32(5, idEvent2_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (idEvent1_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, idEvent1_);
      }
      if (idEvent2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, idEvent2_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Networking.Protocols.Protobuf.AthletesModel.Child)) {
        return super.equals(obj);
      }
      Networking.Protocols.Protobuf.AthletesModel.Child other = (Networking.Protocols.Protobuf.AthletesModel.Child) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (getIdEvent1()
          != other.getIdEvent1()) return false;
      if (getIdEvent2()
          != other.getIdEvent2()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + IDEVENT1_FIELD_NUMBER;
      hash = (53 * hash) + getIdEvent1();
      hash = (37 * hash) + IDEVENT2_FIELD_NUMBER;
      hash = (53 * hash) + getIdEvent2();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Child parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Networking.Protocols.Protobuf.AthletesModel.Child prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Networking.Protocols.Protobuf.Child}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Networking.Protocols.Protobuf.Child)
        Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Child_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Child_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Networking.Protocols.Protobuf.AthletesModel.Child.class, Networking.Protocols.Protobuf.AthletesModel.Child.Builder.class);
      }

      // Construct using Networking.Protocols.Protobuf.AthletesModel.Child.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        name_ = "";

        age_ = 0;

        idEvent1_ = 0;

        idEvent2_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Child_descriptor;
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Child getDefaultInstanceForType() {
        return Networking.Protocols.Protobuf.AthletesModel.Child.getDefaultInstance();
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Child build() {
        Networking.Protocols.Protobuf.AthletesModel.Child result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Child buildPartial() {
        Networking.Protocols.Protobuf.AthletesModel.Child result = new Networking.Protocols.Protobuf.AthletesModel.Child(this);
        result.id_ = id_;
        result.name_ = name_;
        result.age_ = age_;
        result.idEvent1_ = idEvent1_;
        result.idEvent2_ = idEvent2_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Networking.Protocols.Protobuf.AthletesModel.Child) {
          return mergeFrom((Networking.Protocols.Protobuf.AthletesModel.Child)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Networking.Protocols.Protobuf.AthletesModel.Child other) {
        if (other == Networking.Protocols.Protobuf.AthletesModel.Child.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.getIdEvent1() != 0) {
          setIdEvent1(other.getIdEvent1());
        }
        if (other.getIdEvent2() != 0) {
          setIdEvent2(other.getIdEvent2());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Networking.Protocols.Protobuf.AthletesModel.Child parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Networking.Protocols.Protobuf.AthletesModel.Child) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <code>int32 age = 3;</code>
       * @return The age.
       */
      public int getAge() {
        return age_;
      }
      /**
       * <code>int32 age = 3;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 age = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int idEvent1_ ;
      /**
       * <code>int32 idEvent1 = 4;</code>
       * @return The idEvent1.
       */
      public int getIdEvent1() {
        return idEvent1_;
      }
      /**
       * <code>int32 idEvent1 = 4;</code>
       * @param value The idEvent1 to set.
       * @return This builder for chaining.
       */
      public Builder setIdEvent1(int value) {
        
        idEvent1_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idEvent1 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdEvent1() {
        
        idEvent1_ = 0;
        onChanged();
        return this;
      }

      private int idEvent2_ ;
      /**
       * <code>int32 idEvent2 = 5;</code>
       * @return The idEvent2.
       */
      public int getIdEvent2() {
        return idEvent2_;
      }
      /**
       * <code>int32 idEvent2 = 5;</code>
       * @param value The idEvent2 to set.
       * @return This builder for chaining.
       */
      public Builder setIdEvent2(int value) {
        
        idEvent2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 idEvent2 = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdEvent2() {
        
        idEvent2_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Networking.Protocols.Protobuf.Child)
    }

    // @@protoc_insertion_point(class_scope:Networking.Protocols.Protobuf.Child)
    private static final Networking.Protocols.Protobuf.AthletesModel.Child DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Networking.Protocols.Protobuf.AthletesModel.Child();
    }

    public static Networking.Protocols.Protobuf.AthletesModel.Child getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Child>
        PARSER = new com.google.protobuf.AbstractParser<Child>() {
      @java.lang.Override
      public Child parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Child(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Child> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Child> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Networking.Protocols.Protobuf.AthletesModel.Child getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AdminOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Networking.Protocols.Protobuf.Admin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code Networking.Protocols.Protobuf.Admin}
   */
  public  static final class Admin extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Networking.Protocols.Protobuf.Admin)
      AdminOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Admin.newBuilder() to construct.
    private Admin(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Admin() {
      id_ = "";
      password_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Admin();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Admin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              password_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Admin_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Admin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Networking.Protocols.Protobuf.AthletesModel.Admin.class, Networking.Protocols.Protobuf.AthletesModel.Admin.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private volatile java.lang.Object password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getPasswordBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, password_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getPasswordBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, password_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Networking.Protocols.Protobuf.AthletesModel.Admin)) {
        return super.equals(obj);
      }
      Networking.Protocols.Protobuf.AthletesModel.Admin other = (Networking.Protocols.Protobuf.AthletesModel.Admin) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Admin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Networking.Protocols.Protobuf.AthletesModel.Admin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Networking.Protocols.Protobuf.Admin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Networking.Protocols.Protobuf.Admin)
        Networking.Protocols.Protobuf.AthletesModel.AdminOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Admin_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Admin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Networking.Protocols.Protobuf.AthletesModel.Admin.class, Networking.Protocols.Protobuf.AthletesModel.Admin.Builder.class);
      }

      // Construct using Networking.Protocols.Protobuf.AthletesModel.Admin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        password_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Admin_descriptor;
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Admin getDefaultInstanceForType() {
        return Networking.Protocols.Protobuf.AthletesModel.Admin.getDefaultInstance();
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Admin build() {
        Networking.Protocols.Protobuf.AthletesModel.Admin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Admin buildPartial() {
        Networking.Protocols.Protobuf.AthletesModel.Admin result = new Networking.Protocols.Protobuf.AthletesModel.Admin(this);
        result.id_ = id_;
        result.password_ = password_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Networking.Protocols.Protobuf.AthletesModel.Admin) {
          return mergeFrom((Networking.Protocols.Protobuf.AthletesModel.Admin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Networking.Protocols.Protobuf.AthletesModel.Admin other) {
        if (other == Networking.Protocols.Protobuf.AthletesModel.Admin.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Networking.Protocols.Protobuf.AthletesModel.Admin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Networking.Protocols.Protobuf.AthletesModel.Admin) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        password_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        
        password_ = getDefaultInstance().getPassword();
        onChanged();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        password_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Networking.Protocols.Protobuf.Admin)
    }

    // @@protoc_insertion_point(class_scope:Networking.Protocols.Protobuf.Admin)
    private static final Networking.Protocols.Protobuf.AthletesModel.Admin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Networking.Protocols.Protobuf.AthletesModel.Admin();
    }

    public static Networking.Protocols.Protobuf.AthletesModel.Admin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Admin>
        PARSER = new com.google.protobuf.AbstractParser<Admin>() {
      @java.lang.Override
      public Admin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Admin(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Admin> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Admin> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Networking.Protocols.Protobuf.AthletesModel.Admin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Networking.Protocols.Protobuf.Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 ageMin = 2;</code>
     * @return The ageMin.
     */
    int getAgeMin();

    /**
     * <code>int32 ageMax = 3;</code>
     * @return The ageMax.
     */
    int getAgeMax();

    /**
     * <code>int32 distance = 4;</code>
     * @return The distance.
     */
    int getDistance();

    /**
     * <code>int32 no = 5;</code>
     * @return The no.
     */
    int getNo();
  }
  /**
   * Protobuf type {@code Networking.Protocols.Protobuf.Event}
   */
  public  static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Networking.Protocols.Protobuf.Event)
      EventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Event();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              ageMin_ = input.readInt32();
              break;
            }
            case 24: {

              ageMax_ = input.readInt32();
              break;
            }
            case 32: {

              distance_ = input.readInt32();
              break;
            }
            case 40: {

              no_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Networking.Protocols.Protobuf.AthletesModel.Event.class, Networking.Protocols.Protobuf.AthletesModel.Event.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int AGEMIN_FIELD_NUMBER = 2;
    private int ageMin_;
    /**
     * <code>int32 ageMin = 2;</code>
     * @return The ageMin.
     */
    public int getAgeMin() {
      return ageMin_;
    }

    public static final int AGEMAX_FIELD_NUMBER = 3;
    private int ageMax_;
    /**
     * <code>int32 ageMax = 3;</code>
     * @return The ageMax.
     */
    public int getAgeMax() {
      return ageMax_;
    }

    public static final int DISTANCE_FIELD_NUMBER = 4;
    private int distance_;
    /**
     * <code>int32 distance = 4;</code>
     * @return The distance.
     */
    public int getDistance() {
      return distance_;
    }

    public static final int NO_FIELD_NUMBER = 5;
    private int no_;
    /**
     * <code>int32 no = 5;</code>
     * @return The no.
     */
    public int getNo() {
      return no_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (ageMin_ != 0) {
        output.writeInt32(2, ageMin_);
      }
      if (ageMax_ != 0) {
        output.writeInt32(3, ageMax_);
      }
      if (distance_ != 0) {
        output.writeInt32(4, distance_);
      }
      if (no_ != 0) {
        output.writeInt32(5, no_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (ageMin_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, ageMin_);
      }
      if (ageMax_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, ageMax_);
      }
      if (distance_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, distance_);
      }
      if (no_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, no_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Networking.Protocols.Protobuf.AthletesModel.Event)) {
        return super.equals(obj);
      }
      Networking.Protocols.Protobuf.AthletesModel.Event other = (Networking.Protocols.Protobuf.AthletesModel.Event) obj;

      if (getId()
          != other.getId()) return false;
      if (getAgeMin()
          != other.getAgeMin()) return false;
      if (getAgeMax()
          != other.getAgeMax()) return false;
      if (getDistance()
          != other.getDistance()) return false;
      if (getNo()
          != other.getNo()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + AGEMIN_FIELD_NUMBER;
      hash = (53 * hash) + getAgeMin();
      hash = (37 * hash) + AGEMAX_FIELD_NUMBER;
      hash = (53 * hash) + getAgeMax();
      hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
      hash = (53 * hash) + getDistance();
      hash = (37 * hash) + NO_FIELD_NUMBER;
      hash = (53 * hash) + getNo();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesModel.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Networking.Protocols.Protobuf.AthletesModel.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Networking.Protocols.Protobuf.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Networking.Protocols.Protobuf.Event)
        Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Event_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Networking.Protocols.Protobuf.AthletesModel.Event.class, Networking.Protocols.Protobuf.AthletesModel.Event.Builder.class);
      }

      // Construct using Networking.Protocols.Protobuf.AthletesModel.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        ageMin_ = 0;

        ageMax_ = 0;

        distance_ = 0;

        no_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Networking.Protocols.Protobuf.AthletesModel.internal_static_Networking_Protocols_Protobuf_Event_descriptor;
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Event getDefaultInstanceForType() {
        return Networking.Protocols.Protobuf.AthletesModel.Event.getDefaultInstance();
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Event build() {
        Networking.Protocols.Protobuf.AthletesModel.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesModel.Event buildPartial() {
        Networking.Protocols.Protobuf.AthletesModel.Event result = new Networking.Protocols.Protobuf.AthletesModel.Event(this);
        result.id_ = id_;
        result.ageMin_ = ageMin_;
        result.ageMax_ = ageMax_;
        result.distance_ = distance_;
        result.no_ = no_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Networking.Protocols.Protobuf.AthletesModel.Event) {
          return mergeFrom((Networking.Protocols.Protobuf.AthletesModel.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Networking.Protocols.Protobuf.AthletesModel.Event other) {
        if (other == Networking.Protocols.Protobuf.AthletesModel.Event.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getAgeMin() != 0) {
          setAgeMin(other.getAgeMin());
        }
        if (other.getAgeMax() != 0) {
          setAgeMax(other.getAgeMax());
        }
        if (other.getDistance() != 0) {
          setDistance(other.getDistance());
        }
        if (other.getNo() != 0) {
          setNo(other.getNo());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Networking.Protocols.Protobuf.AthletesModel.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Networking.Protocols.Protobuf.AthletesModel.Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int ageMin_ ;
      /**
       * <code>int32 ageMin = 2;</code>
       * @return The ageMin.
       */
      public int getAgeMin() {
        return ageMin_;
      }
      /**
       * <code>int32 ageMin = 2;</code>
       * @param value The ageMin to set.
       * @return This builder for chaining.
       */
      public Builder setAgeMin(int value) {
        
        ageMin_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ageMin = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgeMin() {
        
        ageMin_ = 0;
        onChanged();
        return this;
      }

      private int ageMax_ ;
      /**
       * <code>int32 ageMax = 3;</code>
       * @return The ageMax.
       */
      public int getAgeMax() {
        return ageMax_;
      }
      /**
       * <code>int32 ageMax = 3;</code>
       * @param value The ageMax to set.
       * @return This builder for chaining.
       */
      public Builder setAgeMax(int value) {
        
        ageMax_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ageMax = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAgeMax() {
        
        ageMax_ = 0;
        onChanged();
        return this;
      }

      private int distance_ ;
      /**
       * <code>int32 distance = 4;</code>
       * @return The distance.
       */
      public int getDistance() {
        return distance_;
      }
      /**
       * <code>int32 distance = 4;</code>
       * @param value The distance to set.
       * @return This builder for chaining.
       */
      public Builder setDistance(int value) {
        
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 distance = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDistance() {
        
        distance_ = 0;
        onChanged();
        return this;
      }

      private int no_ ;
      /**
       * <code>int32 no = 5;</code>
       * @return The no.
       */
      public int getNo() {
        return no_;
      }
      /**
       * <code>int32 no = 5;</code>
       * @param value The no to set.
       * @return This builder for chaining.
       */
      public Builder setNo(int value) {
        
        no_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 no = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNo() {
        
        no_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Networking.Protocols.Protobuf.Event)
    }

    // @@protoc_insertion_point(class_scope:Networking.Protocols.Protobuf.Event)
    private static final Networking.Protocols.Protobuf.AthletesModel.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Networking.Protocols.Protobuf.AthletesModel.Event();
    }

    public static Networking.Protocols.Protobuf.AthletesModel.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      @java.lang.Override
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Networking.Protocols.Protobuf.AthletesModel.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Networking_Protocols_Protobuf_Child_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Networking_Protocols_Protobuf_Child_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Networking_Protocols_Protobuf_Admin_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Networking_Protocols_Protobuf_Admin_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Networking_Protocols_Protobuf_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Networking_Protocols_Protobuf_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023AthletesModel.proto\022\035Networking.Protoc" +
      "ols.Protobuf\"R\n\005Child\022\n\n\002id\030\001 \001(\005\022\014\n\004nam" +
      "e\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\020\n\010idEvent1\030\004 \001(\005\022\020" +
      "\n\010idEvent2\030\005 \001(\005\"%\n\005Admin\022\n\n\002id\030\001 \001(\t\022\020\n" +
      "\010password\030\002 \001(\t\"Q\n\005Event\022\n\n\002id\030\001 \001(\005\022\016\n\006" +
      "ageMin\030\002 \001(\005\022\016\n\006ageMax\030\003 \001(\005\022\020\n\010distance" +
      "\030\004 \001(\005\022\n\n\002no\030\005 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Networking_Protocols_Protobuf_Child_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Networking_Protocols_Protobuf_Child_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Networking_Protocols_Protobuf_Child_descriptor,
        new java.lang.String[] { "Id", "Name", "Age", "IdEvent1", "IdEvent2", });
    internal_static_Networking_Protocols_Protobuf_Admin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Networking_Protocols_Protobuf_Admin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Networking_Protocols_Protobuf_Admin_descriptor,
        new java.lang.String[] { "Id", "Password", });
    internal_static_Networking_Protocols_Protobuf_Event_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Networking_Protocols_Protobuf_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Networking_Protocols_Protobuf_Event_descriptor,
        new java.lang.String[] { "Id", "AgeMin", "AgeMax", "Distance", "No", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
