// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AthletesResponse.proto

package Networking.Protocols.Protobuf;

public final class AthletesResponseOuterClass {
  private AthletesResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AthletesResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Networking.Protocols.Protobuf.AthletesResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
     * @return The type.
     */
    Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType getType();

    /**
     * <code>string error = 2;</code>
     * @return The error.
     */
    java.lang.String getError();
    /**
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    com.google.protobuf.ByteString
        getErrorBytes();

    /**
     * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
     * @return Whether the child field is set.
     */
    boolean hasChild();
    /**
     * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
     * @return The child.
     */
    Networking.Protocols.Protobuf.AthletesModel.Child getChild();
    /**
     * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
     */
    Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder getChildOrBuilder();

    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    java.util.List<Networking.Protocols.Protobuf.AthletesModel.Event> 
        getListOfEventsList();
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    Networking.Protocols.Protobuf.AthletesModel.Event getListOfEvents(int index);
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    int getListOfEventsCount();
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    java.util.List<? extends Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder> 
        getListOfEventsOrBuilderList();
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder getListOfEventsOrBuilder(
        int index);

    /**
     * <code>int32 childCount = 5;</code>
     * @return The childCount.
     */
    int getChildCount();

    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    java.util.List<Networking.Protocols.Protobuf.AthletesModel.Child> 
        getListOfChildrenList();
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    Networking.Protocols.Protobuf.AthletesModel.Child getListOfChildren(int index);
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    int getListOfChildrenCount();
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    java.util.List<? extends Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder> 
        getListOfChildrenOrBuilderList();
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder getListOfChildrenOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Networking.Protocols.Protobuf.AthletesResponse}
   */
  public  static final class AthletesResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Networking.Protocols.Protobuf.AthletesResponse)
      AthletesResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AthletesResponse.newBuilder() to construct.
    private AthletesResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AthletesResponse() {
      type_ = 0;
      error_ = "";
      listOfEvents_ = java.util.Collections.emptyList();
      listOfChildren_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AthletesResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AthletesResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              error_ = s;
              break;
            }
            case 26: {
              Networking.Protocols.Protobuf.AthletesModel.Child.Builder subBuilder = null;
              if (child_ != null) {
                subBuilder = child_.toBuilder();
              }
              child_ = input.readMessage(Networking.Protocols.Protobuf.AthletesModel.Child.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(child_);
                child_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                listOfEvents_ = new java.util.ArrayList<Networking.Protocols.Protobuf.AthletesModel.Event>();
                mutable_bitField0_ |= 0x00000001;
              }
              listOfEvents_.add(
                  input.readMessage(Networking.Protocols.Protobuf.AthletesModel.Event.parser(), extensionRegistry));
              break;
            }
            case 40: {

              childCount_ = input.readInt32();
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                listOfChildren_ = new java.util.ArrayList<Networking.Protocols.Protobuf.AthletesModel.Child>();
                mutable_bitField0_ |= 0x00000002;
              }
              listOfChildren_.add(
                  input.readMessage(Networking.Protocols.Protobuf.AthletesModel.Child.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          listOfEvents_ = java.util.Collections.unmodifiableList(listOfEvents_);
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          listOfChildren_ = java.util.Collections.unmodifiableList(listOfChildren_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Networking.Protocols.Protobuf.AthletesResponseOuterClass.internal_static_Networking_Protocols_Protobuf_AthletesResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Networking.Protocols.Protobuf.AthletesResponseOuterClass.internal_static_Networking_Protocols_Protobuf_AthletesResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.class, Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.Builder.class);
    }

    /**
     * Protobuf enum {@code Networking.Protocols.Protobuf.AthletesResponse.ResponseType}
     */
    public enum ResponseType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Unknown = 0;</code>
       */
      Unknown(0),
      /**
       * <code>Ok = 1;</code>
       */
      Ok(1),
      /**
       * <code>Error = 2;</code>
       */
      Error(2),
      /**
       * <code>NewChild = 3;</code>
       */
      NewChild(3),
      /**
       * <code>ListOfEvents = 4;</code>
       */
      ListOfEvents(4),
      /**
       * <code>CounterOfChildren = 5;</code>
       */
      CounterOfChildren(5),
      /**
       * <code>ListOfChildren = 6;</code>
       */
      ListOfChildren(6),
      /**
       * <code>SavedChild = 7;</code>
       */
      SavedChild(7),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Unknown = 0;</code>
       */
      public static final int Unknown_VALUE = 0;
      /**
       * <code>Ok = 1;</code>
       */
      public static final int Ok_VALUE = 1;
      /**
       * <code>Error = 2;</code>
       */
      public static final int Error_VALUE = 2;
      /**
       * <code>NewChild = 3;</code>
       */
      public static final int NewChild_VALUE = 3;
      /**
       * <code>ListOfEvents = 4;</code>
       */
      public static final int ListOfEvents_VALUE = 4;
      /**
       * <code>CounterOfChildren = 5;</code>
       */
      public static final int CounterOfChildren_VALUE = 5;
      /**
       * <code>ListOfChildren = 6;</code>
       */
      public static final int ListOfChildren_VALUE = 6;
      /**
       * <code>SavedChild = 7;</code>
       */
      public static final int SavedChild_VALUE = 7;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ResponseType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static ResponseType forNumber(int value) {
        switch (value) {
          case 0: return Unknown;
          case 1: return Ok;
          case 2: return Error;
          case 3: return NewChild;
          case 4: return ListOfEvents;
          case 5: return CounterOfChildren;
          case 6: return ListOfChildren;
          case 7: return SavedChild;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ResponseType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
              public ResponseType findValueByNumber(int number) {
                return ResponseType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final ResponseType[] VALUES = values();

      public static ResponseType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ResponseType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Networking.Protocols.Protobuf.AthletesResponse.ResponseType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
     * @return The type.
     */
    public Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType getType() {
      @SuppressWarnings("deprecation")
      Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType result = Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType.valueOf(type_);
      return result == null ? Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType.UNRECOGNIZED : result;
    }

    public static final int ERROR_FIELD_NUMBER = 2;
    private volatile java.lang.Object error_;
    /**
     * <code>string error = 2;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      }
    }
    /**
     * <code>string error = 2;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHILD_FIELD_NUMBER = 3;
    private Networking.Protocols.Protobuf.AthletesModel.Child child_;
    /**
     * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
     * @return Whether the child field is set.
     */
    public boolean hasChild() {
      return child_ != null;
    }
    /**
     * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
     * @return The child.
     */
    public Networking.Protocols.Protobuf.AthletesModel.Child getChild() {
      return child_ == null ? Networking.Protocols.Protobuf.AthletesModel.Child.getDefaultInstance() : child_;
    }
    /**
     * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
     */
    public Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder getChildOrBuilder() {
      return getChild();
    }

    public static final int LISTOFEVENTS_FIELD_NUMBER = 4;
    private java.util.List<Networking.Protocols.Protobuf.AthletesModel.Event> listOfEvents_;
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    public java.util.List<Networking.Protocols.Protobuf.AthletesModel.Event> getListOfEventsList() {
      return listOfEvents_;
    }
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    public java.util.List<? extends Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder> 
        getListOfEventsOrBuilderList() {
      return listOfEvents_;
    }
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    public int getListOfEventsCount() {
      return listOfEvents_.size();
    }
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    public Networking.Protocols.Protobuf.AthletesModel.Event getListOfEvents(int index) {
      return listOfEvents_.get(index);
    }
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
     */
    public Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder getListOfEventsOrBuilder(
        int index) {
      return listOfEvents_.get(index);
    }

    public static final int CHILDCOUNT_FIELD_NUMBER = 5;
    private int childCount_;
    /**
     * <code>int32 childCount = 5;</code>
     * @return The childCount.
     */
    public int getChildCount() {
      return childCount_;
    }

    public static final int LISTOFCHILDREN_FIELD_NUMBER = 6;
    private java.util.List<Networking.Protocols.Protobuf.AthletesModel.Child> listOfChildren_;
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    public java.util.List<Networking.Protocols.Protobuf.AthletesModel.Child> getListOfChildrenList() {
      return listOfChildren_;
    }
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    public java.util.List<? extends Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder> 
        getListOfChildrenOrBuilderList() {
      return listOfChildren_;
    }
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    public int getListOfChildrenCount() {
      return listOfChildren_.size();
    }
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    public Networking.Protocols.Protobuf.AthletesModel.Child getListOfChildren(int index) {
      return listOfChildren_.get(index);
    }
    /**
     * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
     */
    public Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder getListOfChildrenOrBuilder(
        int index) {
      return listOfChildren_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType.Unknown.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!getErrorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, error_);
      }
      if (child_ != null) {
        output.writeMessage(3, getChild());
      }
      for (int i = 0; i < listOfEvents_.size(); i++) {
        output.writeMessage(4, listOfEvents_.get(i));
      }
      if (childCount_ != 0) {
        output.writeInt32(5, childCount_);
      }
      for (int i = 0; i < listOfChildren_.size(); i++) {
        output.writeMessage(6, listOfChildren_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType.Unknown.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!getErrorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, error_);
      }
      if (child_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getChild());
      }
      for (int i = 0; i < listOfEvents_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, listOfEvents_.get(i));
      }
      if (childCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, childCount_);
      }
      for (int i = 0; i < listOfChildren_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, listOfChildren_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse)) {
        return super.equals(obj);
      }
      Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse other = (Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse) obj;

      if (type_ != other.type_) return false;
      if (!getError()
          .equals(other.getError())) return false;
      if (hasChild() != other.hasChild()) return false;
      if (hasChild()) {
        if (!getChild()
            .equals(other.getChild())) return false;
      }
      if (!getListOfEventsList()
          .equals(other.getListOfEventsList())) return false;
      if (getChildCount()
          != other.getChildCount()) return false;
      if (!getListOfChildrenList()
          .equals(other.getListOfChildrenList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + ERROR_FIELD_NUMBER;
      hash = (53 * hash) + getError().hashCode();
      if (hasChild()) {
        hash = (37 * hash) + CHILD_FIELD_NUMBER;
        hash = (53 * hash) + getChild().hashCode();
      }
      if (getListOfEventsCount() > 0) {
        hash = (37 * hash) + LISTOFEVENTS_FIELD_NUMBER;
        hash = (53 * hash) + getListOfEventsList().hashCode();
      }
      hash = (37 * hash) + CHILDCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getChildCount();
      if (getListOfChildrenCount() > 0) {
        hash = (37 * hash) + LISTOFCHILDREN_FIELD_NUMBER;
        hash = (53 * hash) + getListOfChildrenList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Networking.Protocols.Protobuf.AthletesResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Networking.Protocols.Protobuf.AthletesResponse)
        Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Networking.Protocols.Protobuf.AthletesResponseOuterClass.internal_static_Networking_Protocols_Protobuf_AthletesResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Networking.Protocols.Protobuf.AthletesResponseOuterClass.internal_static_Networking_Protocols_Protobuf_AthletesResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.class, Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.Builder.class);
      }

      // Construct using Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListOfEventsFieldBuilder();
          getListOfChildrenFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        error_ = "";

        if (childBuilder_ == null) {
          child_ = null;
        } else {
          child_ = null;
          childBuilder_ = null;
        }
        if (listOfEventsBuilder_ == null) {
          listOfEvents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listOfEventsBuilder_.clear();
        }
        childCount_ = 0;

        if (listOfChildrenBuilder_ == null) {
          listOfChildren_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          listOfChildrenBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Networking.Protocols.Protobuf.AthletesResponseOuterClass.internal_static_Networking_Protocols_Protobuf_AthletesResponse_descriptor;
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse getDefaultInstanceForType() {
        return Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.getDefaultInstance();
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse build() {
        Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse buildPartial() {
        Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse result = new Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse(this);
        int from_bitField0_ = bitField0_;
        result.type_ = type_;
        result.error_ = error_;
        if (childBuilder_ == null) {
          result.child_ = child_;
        } else {
          result.child_ = childBuilder_.build();
        }
        if (listOfEventsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            listOfEvents_ = java.util.Collections.unmodifiableList(listOfEvents_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.listOfEvents_ = listOfEvents_;
        } else {
          result.listOfEvents_ = listOfEventsBuilder_.build();
        }
        result.childCount_ = childCount_;
        if (listOfChildrenBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            listOfChildren_ = java.util.Collections.unmodifiableList(listOfChildren_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.listOfChildren_ = listOfChildren_;
        } else {
          result.listOfChildren_ = listOfChildrenBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse) {
          return mergeFrom((Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse other) {
        if (other == Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getError().isEmpty()) {
          error_ = other.error_;
          onChanged();
        }
        if (other.hasChild()) {
          mergeChild(other.getChild());
        }
        if (listOfEventsBuilder_ == null) {
          if (!other.listOfEvents_.isEmpty()) {
            if (listOfEvents_.isEmpty()) {
              listOfEvents_ = other.listOfEvents_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListOfEventsIsMutable();
              listOfEvents_.addAll(other.listOfEvents_);
            }
            onChanged();
          }
        } else {
          if (!other.listOfEvents_.isEmpty()) {
            if (listOfEventsBuilder_.isEmpty()) {
              listOfEventsBuilder_.dispose();
              listOfEventsBuilder_ = null;
              listOfEvents_ = other.listOfEvents_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listOfEventsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListOfEventsFieldBuilder() : null;
            } else {
              listOfEventsBuilder_.addAllMessages(other.listOfEvents_);
            }
          }
        }
        if (other.getChildCount() != 0) {
          setChildCount(other.getChildCount());
        }
        if (listOfChildrenBuilder_ == null) {
          if (!other.listOfChildren_.isEmpty()) {
            if (listOfChildren_.isEmpty()) {
              listOfChildren_ = other.listOfChildren_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureListOfChildrenIsMutable();
              listOfChildren_.addAll(other.listOfChildren_);
            }
            onChanged();
          }
        } else {
          if (!other.listOfChildren_.isEmpty()) {
            if (listOfChildrenBuilder_.isEmpty()) {
              listOfChildrenBuilder_.dispose();
              listOfChildrenBuilder_ = null;
              listOfChildren_ = other.listOfChildren_;
              bitField0_ = (bitField0_ & ~0x00000002);
              listOfChildrenBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListOfChildrenFieldBuilder() : null;
            } else {
              listOfChildrenBuilder_.addAllMessages(other.listOfChildren_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
       * @return The type.
       */
      public Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType getType() {
        @SuppressWarnings("deprecation")
        Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType result = Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType.valueOf(type_);
        return result == null ? Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType.UNRECOGNIZED : result;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse.ResponseType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.AthletesResponse.ResponseType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object error_ = "";
      /**
       * <code>string error = 2;</code>
       * @return The error.
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string error = 2;</code>
       * @return The bytes for error.
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string error = 2;</code>
       * @param value The error to set.
       * @return This builder for chaining.
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearError() {
        
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>string error = 2;</code>
       * @param value The bytes for error to set.
       * @return This builder for chaining.
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        error_ = value;
        onChanged();
        return this;
      }

      private Networking.Protocols.Protobuf.AthletesModel.Child child_;
      private com.google.protobuf.SingleFieldBuilderV3<
          Networking.Protocols.Protobuf.AthletesModel.Child, Networking.Protocols.Protobuf.AthletesModel.Child.Builder, Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder> childBuilder_;
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       * @return Whether the child field is set.
       */
      public boolean hasChild() {
        return childBuilder_ != null || child_ != null;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       * @return The child.
       */
      public Networking.Protocols.Protobuf.AthletesModel.Child getChild() {
        if (childBuilder_ == null) {
          return child_ == null ? Networking.Protocols.Protobuf.AthletesModel.Child.getDefaultInstance() : child_;
        } else {
          return childBuilder_.getMessage();
        }
      }
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       */
      public Builder setChild(Networking.Protocols.Protobuf.AthletesModel.Child value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          child_ = value;
          onChanged();
        } else {
          childBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       */
      public Builder setChild(
          Networking.Protocols.Protobuf.AthletesModel.Child.Builder builderForValue) {
        if (childBuilder_ == null) {
          child_ = builderForValue.build();
          onChanged();
        } else {
          childBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       */
      public Builder mergeChild(Networking.Protocols.Protobuf.AthletesModel.Child value) {
        if (childBuilder_ == null) {
          if (child_ != null) {
            child_ =
              Networking.Protocols.Protobuf.AthletesModel.Child.newBuilder(child_).mergeFrom(value).buildPartial();
          } else {
            child_ = value;
          }
          onChanged();
        } else {
          childBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       */
      public Builder clearChild() {
        if (childBuilder_ == null) {
          child_ = null;
          onChanged();
        } else {
          child_ = null;
          childBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Child.Builder getChildBuilder() {
        
        onChanged();
        return getChildFieldBuilder().getBuilder();
      }
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder getChildOrBuilder() {
        if (childBuilder_ != null) {
          return childBuilder_.getMessageOrBuilder();
        } else {
          return child_ == null ?
              Networking.Protocols.Protobuf.AthletesModel.Child.getDefaultInstance() : child_;
        }
      }
      /**
       * <code>.Networking.Protocols.Protobuf.Child child = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Networking.Protocols.Protobuf.AthletesModel.Child, Networking.Protocols.Protobuf.AthletesModel.Child.Builder, Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder> 
          getChildFieldBuilder() {
        if (childBuilder_ == null) {
          childBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Networking.Protocols.Protobuf.AthletesModel.Child, Networking.Protocols.Protobuf.AthletesModel.Child.Builder, Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder>(
                  getChild(),
                  getParentForChildren(),
                  isClean());
          child_ = null;
        }
        return childBuilder_;
      }

      private java.util.List<Networking.Protocols.Protobuf.AthletesModel.Event> listOfEvents_ =
        java.util.Collections.emptyList();
      private void ensureListOfEventsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          listOfEvents_ = new java.util.ArrayList<Networking.Protocols.Protobuf.AthletesModel.Event>(listOfEvents_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Networking.Protocols.Protobuf.AthletesModel.Event, Networking.Protocols.Protobuf.AthletesModel.Event.Builder, Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder> listOfEventsBuilder_;

      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public java.util.List<Networking.Protocols.Protobuf.AthletesModel.Event> getListOfEventsList() {
        if (listOfEventsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(listOfEvents_);
        } else {
          return listOfEventsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public int getListOfEventsCount() {
        if (listOfEventsBuilder_ == null) {
          return listOfEvents_.size();
        } else {
          return listOfEventsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Event getListOfEvents(int index) {
        if (listOfEventsBuilder_ == null) {
          return listOfEvents_.get(index);
        } else {
          return listOfEventsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder setListOfEvents(
          int index, Networking.Protocols.Protobuf.AthletesModel.Event value) {
        if (listOfEventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListOfEventsIsMutable();
          listOfEvents_.set(index, value);
          onChanged();
        } else {
          listOfEventsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder setListOfEvents(
          int index, Networking.Protocols.Protobuf.AthletesModel.Event.Builder builderForValue) {
        if (listOfEventsBuilder_ == null) {
          ensureListOfEventsIsMutable();
          listOfEvents_.set(index, builderForValue.build());
          onChanged();
        } else {
          listOfEventsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder addListOfEvents(Networking.Protocols.Protobuf.AthletesModel.Event value) {
        if (listOfEventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListOfEventsIsMutable();
          listOfEvents_.add(value);
          onChanged();
        } else {
          listOfEventsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder addListOfEvents(
          int index, Networking.Protocols.Protobuf.AthletesModel.Event value) {
        if (listOfEventsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListOfEventsIsMutable();
          listOfEvents_.add(index, value);
          onChanged();
        } else {
          listOfEventsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder addListOfEvents(
          Networking.Protocols.Protobuf.AthletesModel.Event.Builder builderForValue) {
        if (listOfEventsBuilder_ == null) {
          ensureListOfEventsIsMutable();
          listOfEvents_.add(builderForValue.build());
          onChanged();
        } else {
          listOfEventsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder addListOfEvents(
          int index, Networking.Protocols.Protobuf.AthletesModel.Event.Builder builderForValue) {
        if (listOfEventsBuilder_ == null) {
          ensureListOfEventsIsMutable();
          listOfEvents_.add(index, builderForValue.build());
          onChanged();
        } else {
          listOfEventsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder addAllListOfEvents(
          java.lang.Iterable<? extends Networking.Protocols.Protobuf.AthletesModel.Event> values) {
        if (listOfEventsBuilder_ == null) {
          ensureListOfEventsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, listOfEvents_);
          onChanged();
        } else {
          listOfEventsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder clearListOfEvents() {
        if (listOfEventsBuilder_ == null) {
          listOfEvents_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listOfEventsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Builder removeListOfEvents(int index) {
        if (listOfEventsBuilder_ == null) {
          ensureListOfEventsIsMutable();
          listOfEvents_.remove(index);
          onChanged();
        } else {
          listOfEventsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Event.Builder getListOfEventsBuilder(
          int index) {
        return getListOfEventsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder getListOfEventsOrBuilder(
          int index) {
        if (listOfEventsBuilder_ == null) {
          return listOfEvents_.get(index);  } else {
          return listOfEventsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public java.util.List<? extends Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder> 
           getListOfEventsOrBuilderList() {
        if (listOfEventsBuilder_ != null) {
          return listOfEventsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(listOfEvents_);
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Event.Builder addListOfEventsBuilder() {
        return getListOfEventsFieldBuilder().addBuilder(
            Networking.Protocols.Protobuf.AthletesModel.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Event.Builder addListOfEventsBuilder(
          int index) {
        return getListOfEventsFieldBuilder().addBuilder(
            index, Networking.Protocols.Protobuf.AthletesModel.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Event listOfEvents = 4;</code>
       */
      public java.util.List<Networking.Protocols.Protobuf.AthletesModel.Event.Builder> 
           getListOfEventsBuilderList() {
        return getListOfEventsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Networking.Protocols.Protobuf.AthletesModel.Event, Networking.Protocols.Protobuf.AthletesModel.Event.Builder, Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder> 
          getListOfEventsFieldBuilder() {
        if (listOfEventsBuilder_ == null) {
          listOfEventsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Networking.Protocols.Protobuf.AthletesModel.Event, Networking.Protocols.Protobuf.AthletesModel.Event.Builder, Networking.Protocols.Protobuf.AthletesModel.EventOrBuilder>(
                  listOfEvents_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          listOfEvents_ = null;
        }
        return listOfEventsBuilder_;
      }

      private int childCount_ ;
      /**
       * <code>int32 childCount = 5;</code>
       * @return The childCount.
       */
      public int getChildCount() {
        return childCount_;
      }
      /**
       * <code>int32 childCount = 5;</code>
       * @param value The childCount to set.
       * @return This builder for chaining.
       */
      public Builder setChildCount(int value) {
        
        childCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 childCount = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearChildCount() {
        
        childCount_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<Networking.Protocols.Protobuf.AthletesModel.Child> listOfChildren_ =
        java.util.Collections.emptyList();
      private void ensureListOfChildrenIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          listOfChildren_ = new java.util.ArrayList<Networking.Protocols.Protobuf.AthletesModel.Child>(listOfChildren_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Networking.Protocols.Protobuf.AthletesModel.Child, Networking.Protocols.Protobuf.AthletesModel.Child.Builder, Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder> listOfChildrenBuilder_;

      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public java.util.List<Networking.Protocols.Protobuf.AthletesModel.Child> getListOfChildrenList() {
        if (listOfChildrenBuilder_ == null) {
          return java.util.Collections.unmodifiableList(listOfChildren_);
        } else {
          return listOfChildrenBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public int getListOfChildrenCount() {
        if (listOfChildrenBuilder_ == null) {
          return listOfChildren_.size();
        } else {
          return listOfChildrenBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Child getListOfChildren(int index) {
        if (listOfChildrenBuilder_ == null) {
          return listOfChildren_.get(index);
        } else {
          return listOfChildrenBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder setListOfChildren(
          int index, Networking.Protocols.Protobuf.AthletesModel.Child value) {
        if (listOfChildrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListOfChildrenIsMutable();
          listOfChildren_.set(index, value);
          onChanged();
        } else {
          listOfChildrenBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder setListOfChildren(
          int index, Networking.Protocols.Protobuf.AthletesModel.Child.Builder builderForValue) {
        if (listOfChildrenBuilder_ == null) {
          ensureListOfChildrenIsMutable();
          listOfChildren_.set(index, builderForValue.build());
          onChanged();
        } else {
          listOfChildrenBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder addListOfChildren(Networking.Protocols.Protobuf.AthletesModel.Child value) {
        if (listOfChildrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListOfChildrenIsMutable();
          listOfChildren_.add(value);
          onChanged();
        } else {
          listOfChildrenBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder addListOfChildren(
          int index, Networking.Protocols.Protobuf.AthletesModel.Child value) {
        if (listOfChildrenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListOfChildrenIsMutable();
          listOfChildren_.add(index, value);
          onChanged();
        } else {
          listOfChildrenBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder addListOfChildren(
          Networking.Protocols.Protobuf.AthletesModel.Child.Builder builderForValue) {
        if (listOfChildrenBuilder_ == null) {
          ensureListOfChildrenIsMutable();
          listOfChildren_.add(builderForValue.build());
          onChanged();
        } else {
          listOfChildrenBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder addListOfChildren(
          int index, Networking.Protocols.Protobuf.AthletesModel.Child.Builder builderForValue) {
        if (listOfChildrenBuilder_ == null) {
          ensureListOfChildrenIsMutable();
          listOfChildren_.add(index, builderForValue.build());
          onChanged();
        } else {
          listOfChildrenBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder addAllListOfChildren(
          java.lang.Iterable<? extends Networking.Protocols.Protobuf.AthletesModel.Child> values) {
        if (listOfChildrenBuilder_ == null) {
          ensureListOfChildrenIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, listOfChildren_);
          onChanged();
        } else {
          listOfChildrenBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder clearListOfChildren() {
        if (listOfChildrenBuilder_ == null) {
          listOfChildren_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          listOfChildrenBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Builder removeListOfChildren(int index) {
        if (listOfChildrenBuilder_ == null) {
          ensureListOfChildrenIsMutable();
          listOfChildren_.remove(index);
          onChanged();
        } else {
          listOfChildrenBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Child.Builder getListOfChildrenBuilder(
          int index) {
        return getListOfChildrenFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder getListOfChildrenOrBuilder(
          int index) {
        if (listOfChildrenBuilder_ == null) {
          return listOfChildren_.get(index);  } else {
          return listOfChildrenBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public java.util.List<? extends Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder> 
           getListOfChildrenOrBuilderList() {
        if (listOfChildrenBuilder_ != null) {
          return listOfChildrenBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(listOfChildren_);
        }
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Child.Builder addListOfChildrenBuilder() {
        return getListOfChildrenFieldBuilder().addBuilder(
            Networking.Protocols.Protobuf.AthletesModel.Child.getDefaultInstance());
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public Networking.Protocols.Protobuf.AthletesModel.Child.Builder addListOfChildrenBuilder(
          int index) {
        return getListOfChildrenFieldBuilder().addBuilder(
            index, Networking.Protocols.Protobuf.AthletesModel.Child.getDefaultInstance());
      }
      /**
       * <code>repeated .Networking.Protocols.Protobuf.Child listOfChildren = 6;</code>
       */
      public java.util.List<Networking.Protocols.Protobuf.AthletesModel.Child.Builder> 
           getListOfChildrenBuilderList() {
        return getListOfChildrenFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Networking.Protocols.Protobuf.AthletesModel.Child, Networking.Protocols.Protobuf.AthletesModel.Child.Builder, Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder> 
          getListOfChildrenFieldBuilder() {
        if (listOfChildrenBuilder_ == null) {
          listOfChildrenBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Networking.Protocols.Protobuf.AthletesModel.Child, Networking.Protocols.Protobuf.AthletesModel.Child.Builder, Networking.Protocols.Protobuf.AthletesModel.ChildOrBuilder>(
                  listOfChildren_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          listOfChildren_ = null;
        }
        return listOfChildrenBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Networking.Protocols.Protobuf.AthletesResponse)
    }

    // @@protoc_insertion_point(class_scope:Networking.Protocols.Protobuf.AthletesResponse)
    private static final Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse();
    }

    public static Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AthletesResponse>
        PARSER = new com.google.protobuf.AbstractParser<AthletesResponse>() {
      @java.lang.Override
      public AthletesResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AthletesResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AthletesResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AthletesResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Networking.Protocols.Protobuf.AthletesResponseOuterClass.AthletesResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Networking_Protocols_Protobuf_AthletesResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Networking_Protocols_Protobuf_AthletesResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026AthletesResponse.proto\022\035Networking.Pro" +
      "tocols.Protobuf\032\023AthletesModel.proto\"\274\003\n" +
      "\020AthletesResponse\022J\n\004type\030\001 \001(\0162<.Networ" +
      "king.Protocols.Protobuf.AthletesResponse" +
      ".ResponseType\022\r\n\005error\030\002 \001(\t\0223\n\005child\030\003 " +
      "\001(\0132$.Networking.Protocols.Protobuf.Chil" +
      "d\022:\n\014listOfEvents\030\004 \003(\0132$.Networking.Pro" +
      "tocols.Protobuf.Event\022\022\n\nchildCount\030\005 \001(" +
      "\005\022<\n\016listOfChildren\030\006 \003(\0132$.Networking.P" +
      "rotocols.Protobuf.Child\"\211\001\n\014ResponseType" +
      "\022\013\n\007Unknown\020\000\022\006\n\002Ok\020\001\022\t\n\005Error\020\002\022\014\n\010NewC" +
      "hild\020\003\022\020\n\014ListOfEvents\020\004\022\025\n\021CounterOfChi" +
      "ldren\020\005\022\022\n\016ListOfChildren\020\006\022\016\n\nSavedChil" +
      "d\020\007b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Networking.Protocols.Protobuf.AthletesModel.getDescriptor(),
        });
    internal_static_Networking_Protocols_Protobuf_AthletesResponse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Networking_Protocols_Protobuf_AthletesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Networking_Protocols_Protobuf_AthletesResponse_descriptor,
        new java.lang.String[] { "Type", "Error", "Child", "ListOfEvents", "ChildCount", "ListOfChildren", });
    Networking.Protocols.Protobuf.AthletesModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
