// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AthletesRequest.proto

package protobuf;

public final class AthletesRequestOuterClass {
  private AthletesRequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AthletesRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.AthletesRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
     * @return The type.
     */
    protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType getType();

    /**
     * <code>.protobuf.Admin user = 2;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>.protobuf.Admin user = 2;</code>
     * @return The user.
     */
    protobuf.AthletesModel.Admin getUser();
    /**
     * <code>.protobuf.Admin user = 2;</code>
     */
    protobuf.AthletesModel.AdminOrBuilder getUserOrBuilder();

    /**
     * <code>.protobuf.Child child = 3;</code>
     * @return Whether the child field is set.
     */
    boolean hasChild();
    /**
     * <code>.protobuf.Child child = 3;</code>
     * @return The child.
     */
    protobuf.AthletesModel.Child getChild();
    /**
     * <code>.protobuf.Child child = 3;</code>
     */
    protobuf.AthletesModel.ChildOrBuilder getChildOrBuilder();

    /**
     * <code>int32 eventID = 4;</code>
     * @return The eventID.
     */
    int getEventID();

    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code protobuf.AthletesRequest}
   */
  public  static final class AthletesRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.AthletesRequest)
      AthletesRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AthletesRequest.newBuilder() to construct.
    private AthletesRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AthletesRequest() {
      type_ = 0;
      data_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AthletesRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AthletesRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              protobuf.AthletesModel.Admin.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(protobuf.AthletesModel.Admin.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              protobuf.AthletesModel.Child.Builder subBuilder = null;
              if (child_ != null) {
                subBuilder = child_.toBuilder();
              }
              child_ = input.readMessage(protobuf.AthletesModel.Child.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(child_);
                child_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              eventID_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.AthletesRequestOuterClass.internal_static_protobuf_AthletesRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.AthletesRequestOuterClass.internal_static_protobuf_AthletesRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.AthletesRequestOuterClass.AthletesRequest.class, protobuf.AthletesRequestOuterClass.AthletesRequest.Builder.class);
    }

    /**
     * Protobuf enum {@code protobuf.AthletesRequest.RequestType}
     */
    public enum RequestType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>Unknown = 0;</code>
       */
      Unknown(0),
      /**
       * <code>Login = 1;</code>
       */
      Login(1),
      /**
       * <code>Logout = 2;</code>
       */
      Logout(2),
      /**
       * <code>SaveChild = 3;</code>
       */
      SaveChild(3),
      /**
       * <code>FilterChildren = 4;</code>
       */
      FilterChildren(4),
      /**
       * <code>GetEvents = 5;</code>
       */
      GetEvents(5),
      /**
       * <code>CountChildren = 6;</code>
       */
      CountChildren(6),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>Unknown = 0;</code>
       */
      public static final int Unknown_VALUE = 0;
      /**
       * <code>Login = 1;</code>
       */
      public static final int Login_VALUE = 1;
      /**
       * <code>Logout = 2;</code>
       */
      public static final int Logout_VALUE = 2;
      /**
       * <code>SaveChild = 3;</code>
       */
      public static final int SaveChild_VALUE = 3;
      /**
       * <code>FilterChildren = 4;</code>
       */
      public static final int FilterChildren_VALUE = 4;
      /**
       * <code>GetEvents = 5;</code>
       */
      public static final int GetEvents_VALUE = 5;
      /**
       * <code>CountChildren = 6;</code>
       */
      public static final int CountChildren_VALUE = 6;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static RequestType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static RequestType forNumber(int value) {
        switch (value) {
          case 0: return Unknown;
          case 1: return Login;
          case 2: return Logout;
          case 3: return SaveChild;
          case 4: return FilterChildren;
          case 5: return GetEvents;
          case 6: return CountChildren;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          RequestType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
              public RequestType findValueByNumber(int number) {
                return RequestType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.AthletesRequestOuterClass.AthletesRequest.getDescriptor().getEnumTypes().get(0);
      }

      private static final RequestType[] VALUES = values();

      public static RequestType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private RequestType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:protobuf.AthletesRequest.RequestType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
     * @return The type.
     */
    public protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType getType() {
      @SuppressWarnings("deprecation")
      protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType result = protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType.valueOf(type_);
      return result == null ? protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType.UNRECOGNIZED : result;
    }

    public static final int USER_FIELD_NUMBER = 2;
    private protobuf.AthletesModel.Admin user_;
    /**
     * <code>.protobuf.Admin user = 2;</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.protobuf.Admin user = 2;</code>
     * @return The user.
     */
    public protobuf.AthletesModel.Admin getUser() {
      return user_ == null ? protobuf.AthletesModel.Admin.getDefaultInstance() : user_;
    }
    /**
     * <code>.protobuf.Admin user = 2;</code>
     */
    public protobuf.AthletesModel.AdminOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int CHILD_FIELD_NUMBER = 3;
    private protobuf.AthletesModel.Child child_;
    /**
     * <code>.protobuf.Child child = 3;</code>
     * @return Whether the child field is set.
     */
    public boolean hasChild() {
      return child_ != null;
    }
    /**
     * <code>.protobuf.Child child = 3;</code>
     * @return The child.
     */
    public protobuf.AthletesModel.Child getChild() {
      return child_ == null ? protobuf.AthletesModel.Child.getDefaultInstance() : child_;
    }
    /**
     * <code>.protobuf.Child child = 3;</code>
     */
    public protobuf.AthletesModel.ChildOrBuilder getChildOrBuilder() {
      return getChild();
    }

    public static final int EVENTID_FIELD_NUMBER = 4;
    private int eventID_;
    /**
     * <code>int32 eventID = 4;</code>
     * @return The eventID.
     */
    public int getEventID() {
      return eventID_;
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType.Unknown.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (user_ != null) {
        output.writeMessage(2, getUser());
      }
      if (child_ != null) {
        output.writeMessage(3, getChild());
      }
      if (eventID_ != 0) {
        output.writeInt32(4, eventID_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType.Unknown.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUser());
      }
      if (child_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getChild());
      }
      if (eventID_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, eventID_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.AthletesRequestOuterClass.AthletesRequest)) {
        return super.equals(obj);
      }
      protobuf.AthletesRequestOuterClass.AthletesRequest other = (protobuf.AthletesRequestOuterClass.AthletesRequest) obj;

      if (type_ != other.type_) return false;
      if (hasUser() != other.hasUser()) return false;
      if (hasUser()) {
        if (!getUser()
            .equals(other.getUser())) return false;
      }
      if (hasChild() != other.hasChild()) return false;
      if (hasChild()) {
        if (!getChild()
            .equals(other.getChild())) return false;
      }
      if (getEventID()
          != other.getEventID()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      if (hasChild()) {
        hash = (37 * hash) + CHILD_FIELD_NUMBER;
        hash = (53 * hash) + getChild().hashCode();
      }
      hash = (37 * hash) + EVENTID_FIELD_NUMBER;
      hash = (53 * hash) + getEventID();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.AthletesRequestOuterClass.AthletesRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.AthletesRequestOuterClass.AthletesRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.AthletesRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.AthletesRequest)
        protobuf.AthletesRequestOuterClass.AthletesRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.AthletesRequestOuterClass.internal_static_protobuf_AthletesRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.AthletesRequestOuterClass.internal_static_protobuf_AthletesRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.AthletesRequestOuterClass.AthletesRequest.class, protobuf.AthletesRequestOuterClass.AthletesRequest.Builder.class);
      }

      // Construct using protobuf.AthletesRequestOuterClass.AthletesRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        if (childBuilder_ == null) {
          child_ = null;
        } else {
          child_ = null;
          childBuilder_ = null;
        }
        eventID_ = 0;

        data_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.AthletesRequestOuterClass.internal_static_protobuf_AthletesRequest_descriptor;
      }

      @java.lang.Override
      public protobuf.AthletesRequestOuterClass.AthletesRequest getDefaultInstanceForType() {
        return protobuf.AthletesRequestOuterClass.AthletesRequest.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.AthletesRequestOuterClass.AthletesRequest build() {
        protobuf.AthletesRequestOuterClass.AthletesRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.AthletesRequestOuterClass.AthletesRequest buildPartial() {
        protobuf.AthletesRequestOuterClass.AthletesRequest result = new protobuf.AthletesRequestOuterClass.AthletesRequest(this);
        result.type_ = type_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        if (childBuilder_ == null) {
          result.child_ = child_;
        } else {
          result.child_ = childBuilder_.build();
        }
        result.eventID_ = eventID_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.AthletesRequestOuterClass.AthletesRequest) {
          return mergeFrom((protobuf.AthletesRequestOuterClass.AthletesRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.AthletesRequestOuterClass.AthletesRequest other) {
        if (other == protobuf.AthletesRequestOuterClass.AthletesRequest.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (other.hasChild()) {
          mergeChild(other.getChild());
        }
        if (other.getEventID() != 0) {
          setEventID(other.getEventID());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.AthletesRequestOuterClass.AthletesRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.AthletesRequestOuterClass.AthletesRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
       * @return The type.
       */
      public protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType getType() {
        @SuppressWarnings("deprecation")
        protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType result = protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType.valueOf(type_);
        return result == null ? protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType.UNRECOGNIZED : result;
      }
      /**
       * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(protobuf.AthletesRequestOuterClass.AthletesRequest.RequestType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.protobuf.AthletesRequest.RequestType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private protobuf.AthletesModel.Admin user_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.AthletesModel.Admin, protobuf.AthletesModel.Admin.Builder, protobuf.AthletesModel.AdminOrBuilder> userBuilder_;
      /**
       * <code>.protobuf.Admin user = 2;</code>
       * @return Whether the user field is set.
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.protobuf.Admin user = 2;</code>
       * @return The user.
       */
      public protobuf.AthletesModel.Admin getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? protobuf.AthletesModel.Admin.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.protobuf.Admin user = 2;</code>
       */
      public Builder setUser(protobuf.AthletesModel.Admin value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protobuf.Admin user = 2;</code>
       */
      public Builder setUser(
          protobuf.AthletesModel.Admin.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protobuf.Admin user = 2;</code>
       */
      public Builder mergeUser(protobuf.AthletesModel.Admin value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              protobuf.AthletesModel.Admin.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protobuf.Admin user = 2;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protobuf.Admin user = 2;</code>
       */
      public protobuf.AthletesModel.Admin.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.protobuf.Admin user = 2;</code>
       */
      public protobuf.AthletesModel.AdminOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              protobuf.AthletesModel.Admin.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.protobuf.Admin user = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.AthletesModel.Admin, protobuf.AthletesModel.Admin.Builder, protobuf.AthletesModel.AdminOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protobuf.AthletesModel.Admin, protobuf.AthletesModel.Admin.Builder, protobuf.AthletesModel.AdminOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private protobuf.AthletesModel.Child child_;
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.AthletesModel.Child, protobuf.AthletesModel.Child.Builder, protobuf.AthletesModel.ChildOrBuilder> childBuilder_;
      /**
       * <code>.protobuf.Child child = 3;</code>
       * @return Whether the child field is set.
       */
      public boolean hasChild() {
        return childBuilder_ != null || child_ != null;
      }
      /**
       * <code>.protobuf.Child child = 3;</code>
       * @return The child.
       */
      public protobuf.AthletesModel.Child getChild() {
        if (childBuilder_ == null) {
          return child_ == null ? protobuf.AthletesModel.Child.getDefaultInstance() : child_;
        } else {
          return childBuilder_.getMessage();
        }
      }
      /**
       * <code>.protobuf.Child child = 3;</code>
       */
      public Builder setChild(protobuf.AthletesModel.Child value) {
        if (childBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          child_ = value;
          onChanged();
        } else {
          childBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.protobuf.Child child = 3;</code>
       */
      public Builder setChild(
          protobuf.AthletesModel.Child.Builder builderForValue) {
        if (childBuilder_ == null) {
          child_ = builderForValue.build();
          onChanged();
        } else {
          childBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.protobuf.Child child = 3;</code>
       */
      public Builder mergeChild(protobuf.AthletesModel.Child value) {
        if (childBuilder_ == null) {
          if (child_ != null) {
            child_ =
              protobuf.AthletesModel.Child.newBuilder(child_).mergeFrom(value).buildPartial();
          } else {
            child_ = value;
          }
          onChanged();
        } else {
          childBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.protobuf.Child child = 3;</code>
       */
      public Builder clearChild() {
        if (childBuilder_ == null) {
          child_ = null;
          onChanged();
        } else {
          child_ = null;
          childBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.protobuf.Child child = 3;</code>
       */
      public protobuf.AthletesModel.Child.Builder getChildBuilder() {
        
        onChanged();
        return getChildFieldBuilder().getBuilder();
      }
      /**
       * <code>.protobuf.Child child = 3;</code>
       */
      public protobuf.AthletesModel.ChildOrBuilder getChildOrBuilder() {
        if (childBuilder_ != null) {
          return childBuilder_.getMessageOrBuilder();
        } else {
          return child_ == null ?
              protobuf.AthletesModel.Child.getDefaultInstance() : child_;
        }
      }
      /**
       * <code>.protobuf.Child child = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protobuf.AthletesModel.Child, protobuf.AthletesModel.Child.Builder, protobuf.AthletesModel.ChildOrBuilder> 
          getChildFieldBuilder() {
        if (childBuilder_ == null) {
          childBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protobuf.AthletesModel.Child, protobuf.AthletesModel.Child.Builder, protobuf.AthletesModel.ChildOrBuilder>(
                  getChild(),
                  getParentForChildren(),
                  isClean());
          child_ = null;
        }
        return childBuilder_;
      }

      private int eventID_ ;
      /**
       * <code>int32 eventID = 4;</code>
       * @return The eventID.
       */
      public int getEventID() {
        return eventID_;
      }
      /**
       * <code>int32 eventID = 4;</code>
       * @param value The eventID to set.
       * @return This builder for chaining.
       */
      public Builder setEventID(int value) {
        
        eventID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 eventID = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventID() {
        
        eventID_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 5;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.AthletesRequest)
    }

    // @@protoc_insertion_point(class_scope:protobuf.AthletesRequest)
    private static final protobuf.AthletesRequestOuterClass.AthletesRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.AthletesRequestOuterClass.AthletesRequest();
    }

    public static protobuf.AthletesRequestOuterClass.AthletesRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AthletesRequest>
        PARSER = new com.google.protobuf.AbstractParser<AthletesRequest>() {
      @java.lang.Override
      public AthletesRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AthletesRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AthletesRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AthletesRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.AthletesRequestOuterClass.AthletesRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_AthletesRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_AthletesRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025AthletesRequest.proto\022\010protobuf\032\023Athle" +
      "tesModel.proto\"\234\002\n\017AthletesRequest\0223\n\004ty" +
      "pe\030\001 \001(\0162%.protobuf.AthletesRequest.Requ" +
      "estType\022\035\n\004user\030\002 \001(\0132\017.protobuf.Admin\022\036" +
      "\n\005child\030\003 \001(\0132\017.protobuf.Child\022\017\n\007eventI" +
      "D\030\004 \001(\005\022\014\n\004data\030\005 \001(\t\"v\n\013RequestType\022\013\n\007" +
      "Unknown\020\000\022\t\n\005Login\020\001\022\n\n\006Logout\020\002\022\r\n\tSave" +
      "Child\020\003\022\022\n\016FilterChildren\020\004\022\r\n\tGetEvents" +
      "\020\005\022\021\n\rCountChildren\020\006b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.AthletesModel.getDescriptor(),
        });
    internal_static_protobuf_AthletesRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_AthletesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_AthletesRequest_descriptor,
        new java.lang.String[] { "Type", "User", "Child", "EventID", "Data", });
    protobuf.AthletesModel.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
