//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Persistence.Repository.EntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Probe1 { get; set; }
        public Nullable<int> Probe2 { get; set; }
    
        public virtual probe probe { get; set; }
        public virtual probe probe3 { get; set; }
    }
}
