// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: AthletesResponse.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Networking.Protocols.Protobuf {

  /// <summary>Holder for reflection information generated from AthletesResponse.proto</summary>
  public static partial class AthletesResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for AthletesResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AthletesResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZBdGhsZXRlc1Jlc3BvbnNlLnByb3RvEh1OZXR3b3JraW5nLlByb3RvY29s",
            "cy5Qcm90b2J1ZhoTQXRobGV0ZXNNb2RlbC5wcm90byK8AwoQQXRobGV0ZXNS",
            "ZXNwb25zZRJKCgR0eXBlGAEgASgOMjwuTmV0d29ya2luZy5Qcm90b2NvbHMu",
            "UHJvdG9idWYuQXRobGV0ZXNSZXNwb25zZS5SZXNwb25zZVR5cGUSDQoFZXJy",
            "b3IYAiABKAkSMwoFY2hpbGQYAyABKAsyJC5OZXR3b3JraW5nLlByb3RvY29s",
            "cy5Qcm90b2J1Zi5DaGlsZBI6CgxsaXN0T2ZFdmVudHMYBCADKAsyJC5OZXR3",
            "b3JraW5nLlByb3RvY29scy5Qcm90b2J1Zi5FdmVudBISCgpjaGlsZENvdW50",
            "GAUgASgFEjwKDmxpc3RPZkNoaWxkcmVuGAYgAygLMiQuTmV0d29ya2luZy5Q",
            "cm90b2NvbHMuUHJvdG9idWYuQ2hpbGQiiQEKDFJlc3BvbnNlVHlwZRILCgdV",
            "bmtub3duEAASBgoCT2sQARIJCgVFcnJvchACEgwKCE5ld0NoaWxkEAMSEAoM",
            "TGlzdE9mRXZlbnRzEAQSFQoRQ291bnRlck9mQ2hpbGRyZW4QBRISCg5MaXN0",
            "T2ZDaGlsZHJlbhAGEg4KClNhdmVkQ2hpbGQQB2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Networking.Protocols.Protobuf.AthletesModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Networking.Protocols.Protobuf.AthletesResponse), global::Networking.Protocols.Protobuf.AthletesResponse.Parser, new[]{ "Type", "Error", "Child", "ListOfEvents", "ChildCount", "ListOfChildren" }, null, new[]{ typeof(global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AthletesResponse : pb::IMessage<AthletesResponse> {
    private static readonly pb::MessageParser<AthletesResponse> _parser = new pb::MessageParser<AthletesResponse>(() => new AthletesResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AthletesResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Networking.Protocols.Protobuf.AthletesResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AthletesResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AthletesResponse(AthletesResponse other) : this() {
      type_ = other.type_;
      error_ = other.error_;
      child_ = other.child_ != null ? other.child_.Clone() : null;
      listOfEvents_ = other.listOfEvents_.Clone();
      childCount_ = other.childCount_;
      listOfChildren_ = other.listOfChildren_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AthletesResponse Clone() {
      return new AthletesResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType type_ = global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private string error_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Error {
      get { return error_; }
      set {
        error_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "child" field.</summary>
    public const int ChildFieldNumber = 3;
    private global::Networking.Protocols.Protobuf.Child child_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Networking.Protocols.Protobuf.Child Child {
      get { return child_; }
      set {
        child_ = value;
      }
    }

    /// <summary>Field number for the "listOfEvents" field.</summary>
    public const int ListOfEventsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::Networking.Protocols.Protobuf.Event> _repeated_listOfEvents_codec
        = pb::FieldCodec.ForMessage(34, global::Networking.Protocols.Protobuf.Event.Parser);
    private readonly pbc::RepeatedField<global::Networking.Protocols.Protobuf.Event> listOfEvents_ = new pbc::RepeatedField<global::Networking.Protocols.Protobuf.Event>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Networking.Protocols.Protobuf.Event> ListOfEvents {
      get { return listOfEvents_; }
    }

    /// <summary>Field number for the "childCount" field.</summary>
    public const int ChildCountFieldNumber = 5;
    private int childCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ChildCount {
      get { return childCount_; }
      set {
        childCount_ = value;
      }
    }

    /// <summary>Field number for the "listOfChildren" field.</summary>
    public const int ListOfChildrenFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Networking.Protocols.Protobuf.Child> _repeated_listOfChildren_codec
        = pb::FieldCodec.ForMessage(50, global::Networking.Protocols.Protobuf.Child.Parser);
    private readonly pbc::RepeatedField<global::Networking.Protocols.Protobuf.Child> listOfChildren_ = new pbc::RepeatedField<global::Networking.Protocols.Protobuf.Child>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Networking.Protocols.Protobuf.Child> ListOfChildren {
      get { return listOfChildren_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AthletesResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AthletesResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Error != other.Error) return false;
      if (!object.Equals(Child, other.Child)) return false;
      if(!listOfEvents_.Equals(other.listOfEvents_)) return false;
      if (ChildCount != other.ChildCount) return false;
      if(!listOfChildren_.Equals(other.listOfChildren_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType.Unknown) hash ^= Type.GetHashCode();
      if (Error.Length != 0) hash ^= Error.GetHashCode();
      if (child_ != null) hash ^= Child.GetHashCode();
      hash ^= listOfEvents_.GetHashCode();
      if (ChildCount != 0) hash ^= ChildCount.GetHashCode();
      hash ^= listOfChildren_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Error.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Error);
      }
      if (child_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Child);
      }
      listOfEvents_.WriteTo(output, _repeated_listOfEvents_codec);
      if (ChildCount != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ChildCount);
      }
      listOfChildren_.WriteTo(output, _repeated_listOfChildren_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Error.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Error);
      }
      if (child_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Child);
      }
      size += listOfEvents_.CalculateSize(_repeated_listOfEvents_codec);
      if (ChildCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ChildCount);
      }
      size += listOfChildren_.CalculateSize(_repeated_listOfChildren_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AthletesResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType.Unknown) {
        Type = other.Type;
      }
      if (other.Error.Length != 0) {
        Error = other.Error;
      }
      if (other.child_ != null) {
        if (child_ == null) {
          Child = new global::Networking.Protocols.Protobuf.Child();
        }
        Child.MergeFrom(other.Child);
      }
      listOfEvents_.Add(other.listOfEvents_);
      if (other.ChildCount != 0) {
        ChildCount = other.ChildCount;
      }
      listOfChildren_.Add(other.listOfChildren_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Networking.Protocols.Protobuf.AthletesResponse.Types.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            Error = input.ReadString();
            break;
          }
          case 26: {
            if (child_ == null) {
              Child = new global::Networking.Protocols.Protobuf.Child();
            }
            input.ReadMessage(Child);
            break;
          }
          case 34: {
            listOfEvents_.AddEntriesFrom(input, _repeated_listOfEvents_codec);
            break;
          }
          case 40: {
            ChildCount = input.ReadInt32();
            break;
          }
          case 50: {
            listOfChildren_.AddEntriesFrom(input, _repeated_listOfChildren_codec);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AthletesResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum ResponseType {
        [pbr::OriginalName("Unknown")] Unknown = 0,
        [pbr::OriginalName("Ok")] Ok = 1,
        [pbr::OriginalName("Error")] Error = 2,
        [pbr::OriginalName("NewChild")] NewChild = 3,
        [pbr::OriginalName("ListOfEvents")] ListOfEvents = 4,
        [pbr::OriginalName("CounterOfChildren")] CounterOfChildren = 5,
        [pbr::OriginalName("ListOfChildren")] ListOfChildren = 6,
        [pbr::OriginalName("SavedChild")] SavedChild = 7,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
